# Generated by Django 4.0 on 2022-06-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
    ]
