# Generated by Django 4.0 on 2022-06-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_category_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
